// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: link_shortener/v1/link_shortener.proto

package linkShortenerV1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on AddLinkRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *AddLinkRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetLongLink()) < 1 {
		return AddLinkRequestValidationError{
			field:  "LongLink",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// AddLinkRequestValidationError is the validation error returned by
// AddLinkRequest.Validate if the designated constraints aren't met.
type AddLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddLinkRequestValidationError) ErrorName() string { return "AddLinkRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddLinkRequestValidationError{}

// Validate checks the field values on AddLinkResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AddLinkResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddLinkResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// AddLinkResponseValidationError is the validation error returned by
// AddLinkResponse.Validate if the designated constraints aren't met.
type AddLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddLinkResponseValidationError) ErrorName() string { return "AddLinkResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddLinkResponseValidationError{}

// Validate checks the field values on GetLongLinkRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetLongLinkRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetShortLink()) < 1 {
		return GetLongLinkRequestValidationError{
			field:  "ShortLink",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// GetLongLinkRequestValidationError is the validation error returned by
// GetLongLinkRequest.Validate if the designated constraints aren't met.
type GetLongLinkRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLongLinkRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLongLinkRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLongLinkRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLongLinkRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLongLinkRequestValidationError) ErrorName() string {
	return "GetLongLinkRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetLongLinkRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLongLinkRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLongLinkRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLongLinkRequestValidationError{}

// Validate checks the field values on GetLongLinkResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetLongLinkResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetLongLinkResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// GetLongLinkResponseValidationError is the validation error returned by
// GetLongLinkResponse.Validate if the designated constraints aren't met.
type GetLongLinkResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLongLinkResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLongLinkResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLongLinkResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLongLinkResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLongLinkResponseValidationError) ErrorName() string {
	return "GetLongLinkResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLongLinkResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLongLinkResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLongLinkResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLongLinkResponseValidationError{}

// Validate checks the field values on AddLinkResponse_Result with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AddLinkResponse_Result) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ShortLink

	return nil
}

// AddLinkResponse_ResultValidationError is the validation error returned by
// AddLinkResponse_Result.Validate if the designated constraints aren't met.
type AddLinkResponse_ResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddLinkResponse_ResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddLinkResponse_ResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddLinkResponse_ResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddLinkResponse_ResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddLinkResponse_ResultValidationError) ErrorName() string {
	return "AddLinkResponse_ResultValidationError"
}

// Error satisfies the builtin error interface
func (e AddLinkResponse_ResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddLinkResponse_Result.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddLinkResponse_ResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddLinkResponse_ResultValidationError{}

// Validate checks the field values on GetLongLinkResponse_Result with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetLongLinkResponse_Result) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for LongLink

	return nil
}

// GetLongLinkResponse_ResultValidationError is the validation error returned
// by GetLongLinkResponse_Result.Validate if the designated constraints aren't met.
type GetLongLinkResponse_ResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLongLinkResponse_ResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLongLinkResponse_ResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLongLinkResponse_ResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLongLinkResponse_ResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLongLinkResponse_ResultValidationError) ErrorName() string {
	return "GetLongLinkResponse_ResultValidationError"
}

// Error satisfies the builtin error interface
func (e GetLongLinkResponse_ResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLongLinkResponse_Result.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLongLinkResponse_ResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLongLinkResponse_ResultValidationError{}
