# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  revive:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
 
linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - typecheck
#    - dupl # it's very slow, enable if you really know why you need it
    - errcheck
    - goconst
    - goimports
    - megacheck # (staticcheck + gosimple + unused in one linter)
    - gosec
    - revive
    - unused # will be used insted of varcheck + deadcode + structcheck. More info https://github.com/golangci/golangci-lint/issues/1841
    - nilerr
    - wastedassign
    - gocritic
    - prealloc

