version: '3.8'

volumes:
  postgres_volume:


services:
  db:
    image: postgres:14-alpine3.15
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5444:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./configs/postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgresql_exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:sample_pass@db:5432/postgres?sslmode=disable

  pgbouncer:
    image: bitnami/pgbouncer:1.17.0
    environment:
      - "POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}"
      - "POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}"
      - "POSTGRESQL_USERNAME=${POSTGRES_USER}"
      - "POSTGRESQL_HOST=db"
      - "PGBOUNCER_POOL_MODE=transaction"
      - "PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits"
      - "PGBOUNCER_DATABASE=${POSTGRESQL_DATABASE}"
    ports:
      - "6432:6432"
    depends_on:
      - db

  goose:
    build: ./migrations/
    restart: on-failure
    environment:
      DB_HOST: db
    ports:
      - "5446:5432"
    depends_on:
      - pgbouncer

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"

  redis_exporter:
    image: oliver006/redis_exporter:v1.37.0
    command: "--redis.addr=redis://redis:6379 --web.listen-address=0.0.0.0:9121"
    restart: unless-stopped