version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    image: postgres:14-alpine3.15
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "PGDATA=/var/lib/postgresql/data"
    ports:
      - "5444:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./configs/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  pgbouncer:
    image: edoburu/pgbouncer:1.12.0
    environment:
      - "DB_NAME=${POSTGRES_DB}"
      - "DB_USER=${POSTGRES_USER}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "DB_HOST=db"
      - "POOL_MODE=transaction"
    ports:
      - "5445:5432"

#  goose:
#    build: ./migrations/
#    restart: unless-stopped
#    environment:
#      DB_HOST: db
#    ports:
#      - "5446:5432"
#    depends_on:
#      - db

