version: '3'
services:
    db:
        image: postgres:13-alpine
        environment:
            - "POSTGRES_DB=sample_db"
            - "POSTGRES_PASSWORD=sample_pass"
            - "POSTGRES_USER=postgres"
            - "PGDATA=/var/lib/postgresql/data/notification"
        ports:
            - "5444:5432"
        command: ["postgres", "-c", "log_statement=all"]

    pgbouncer:
        image: edoburu/pgbouncer:latest
        environment:
        - "DB_NAME=sample_db"
        - "DB_PASSWORD=sample_pass"
        - "DB_USER=postgres"
        - "DB_HOST=db"
        - "POOL_MODE=transaction"
        ports:
        - "5445:5432"

#    goose:
#        build: ./migrations/
#        environment:
#            DB_HOST: db
#        ports:
#            - "5446:5432"
#        command: [ "postgres", "-c", "log_statement=all" ]
