global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgresql_exporter
    static_configs:
      - targets: ["postgresql_exporter:9187"]
  - job_name: link-shortener
    static_configs:
      - targets: ["localhost:2112"]
