global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/targets/alerts.yml"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: postgresql-exporter
    static_configs:
      - targets: ["postgresql_exporter:9187"]

  - job_name: link-shortener
    static_configs:
      - targets: ["host.docker.internal:2112"]

  - job_name: redis-exporter
    static_configs:
      - targets: [ "redis_exporter:9121" ]