// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/olezhek28/link-shortener/internal/app/repository (interfaces: ILinks)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockILinks is a mock of ILinks interface.
type MockILinks struct {
	ctrl     *gomock.Controller
	recorder *MockILinksMockRecorder
}

// MockILinksMockRecorder is the mock recorder for MockILinks.
type MockILinksMockRecorder struct {
	mock *MockILinks
}

// NewMockILinks creates a new mock instance.
func NewMockILinks(ctrl *gomock.Controller) *MockILinks {
	mock := &MockILinks{ctrl: ctrl}
	mock.recorder = &MockILinksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILinks) EXPECT() *MockILinksMockRecorder {
	return m.recorder
}

// GetLongLink mocks base method.
func (m *MockILinks) GetLongLink(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongLink", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLongLink indicates an expected call of GetLongLink.
func (mr *MockILinksMockRecorder) GetLongLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongLink", reflect.TypeOf((*MockILinks)(nil).GetLongLink), arg0, arg1)
}

// GetShortLink mocks base method.
func (m *MockILinks) GetShortLink(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortLink", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortLink indicates an expected call of GetShortLink.
func (mr *MockILinksMockRecorder) GetShortLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortLink", reflect.TypeOf((*MockILinks)(nil).GetShortLink), arg0, arg1)
}
